// data.js -- generated from the same source data as the iOS app's EndorsementDatabase.swift.
// Do not hand-edit; regenerate from gen_database.py + gen_web_data.py if the data changes.
var ENDORSEMENT_DATA = [
  {
    "id": "A.1",
    "title": "Prerequisites for Practical Test",
    "citation": "14 CFR § 61.39(a)(6)(i),(ii)",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any applicant before a practical test (checkride) for a certificate or rating.",
    "requirements": "Certifies the applicant received and logged training within the 2 calendar months preceding the month of application, in preparation for the test, and is prepared for the required Areas of Operation.",
    "validity": {
      "type": "conditionalWindow",
      "value": null,
      "display": "Valid only if training falls within the 2 calendar months preceding the month of application.",
      "trackable": true
    },
    "notes": "Appears on FAA Form 8710-1/8710-11 as the \"recommended for practical test\" sign-off; combine with A.2 when a knowledge test preceded the practical.",
    "templateText": "I certify that [First name, MI, Last name] has received and logged training time within 2 calendar-months preceding the month of application in preparation for the practical test and [he or she] is prepared for the required practical test for the issuance of [applicable] certificate.",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.2",
    "title": "Review of Knowledge Test Deficiencies",
    "citation": "14 CFR § 61.39(a)(6)(iii)",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Applicant who took the required knowledge test before the practical test.",
    "requirements": "Certifies the applicant has demonstrated satisfactory knowledge of the subject areas marked deficient on the Airman Knowledge Test Report.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Frequently overlooked as a separate line item from A.1 — both are required together whenever a knowledge test preceded the practical test.",
    "templateText": "I certify that [First name, MI, Last name] has demonstrated satisfactory knowledge of the subject areas in which [he or she] was deficient on the [applicable] airman knowledge test.",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.3",
    "title": "Pre-Solo Aeronautical Knowledge Test",
    "citation": "14 CFR § 61.87(b)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Every student pilot, before first solo in a given aircraft.",
    "requirements": "Instructor-written and graded knowledge test covering applicable Part 61/91 rules, airspace and procedures for the solo airport, and the flight characteristics/operating limitations of the specific make and model. Every incorrect answer must be reviewed with the student before solo is authorized.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Not an FAA-administered test — the CFI writes and grades it, specific to the aircraft to be flown.",
    "templateText": "I certify that [First name, MI, Last name] has satisfactorily completed the pre-solo knowledge test of § 61.87(b) for the [make and model] aircraft.",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.4",
    "title": "Pre-Solo Flight Training",
    "citation": "14 CFR § 61.87(c)(1),(2)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Every student pilot, before first solo, per specific make and model.",
    "requirements": "Flight training in the maneuvers/procedures required for the aircraft category (§ 61.87(d)-(m)). For helicopters (§ 61.87(f)): preflight prep, taxi/hover ops, normal and crosswind takeoffs/landings, straight-and-level flight and turns, climbs, traffic pattern operations, collision/windshear/wake-turbulence avoidance, descents, emergency procedures, ground reference maneuvers, hovering and hovering turns, go-arounds, simulated emergencies including autorotational descents with power recovery and power recovery to a hover, rapid decelerations.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Make-and-model specific — an R22 endorsement does not cover R44 solo, and vice versa. SFAR 73 layers additional helicopter-specific requirements on top of this for Robinson aircraft.",
    "templateText": "I certify that [First name, MI, Last name] has received and logged pre-solo flight training for the maneuvers and procedures that are appropriate to the [make and model] aircraft. I have determined [he or she] has demonstrated satisfactory proficiency and safety on the maneuvers and procedures required by § 61.87 in this or similar make and model of aircraft to be flown.",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.5",
    "title": "Pre-Solo Flight Training at Night",
    "citation": "14 CFR § 61.87(o)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student pilot who wants to solo at night.",
    "requirements": "Night flight training on takeoffs, approaches, landings, and go-arounds, plus night navigation training in the vicinity of the airport where solo will occur, for the specific make/model.",
    "validity": {
      "type": "days",
      "value": 90,
      "display": "90 days",
      "trackable": true
    },
    "notes": "Additional and separate from the day pre-solo/solo endorsements, not a substitute for them.",
    "templateText": "I certify that [First name, MI, Last name] has received flight training at night on night flying procedures that include takeoffs, approaches, landings, and go-arounds at night at the [airport name] airport where the solo flight will be conducted; navigation training at night in the vicinity of the [airport name] airport where the solo flight will be conducted. This endorsement expires 90 calendar-days from the date the flight training at night was received.",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.6",
    "title": "Solo Flight, First 90-Day Period",
    "citation": "14 CFR § 61.87(n)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Every student pilot's first solo authorization in a specific make/model.",
    "requirements": "Instructor has trained the student in that make/model (or a similar one), determined proficiency in the required maneuvers/procedures and in the specific make/model, and endorsed the logbook.",
    "validity": {
      "type": "days",
      "value": 90,
      "display": "90 days",
      "trackable": true
    },
    "notes": "Must state the specific make AND model, e.g. \"Robinson R22 Beta II,\" not just \"Robinson\" or \"R22.\"",
    "templateText": "I certify that [First name, MI, Last name] has received the required training to qualify for solo flying. I have determined [he or she] meets the applicable requirements of § 61.87(n) and is proficient to make solo flights in [make and model].",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.7",
    "title": "Solo Flight, Each Additional 90-Day Period",
    "citation": "14 CFR § 61.87(p)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any student pilot whose 90-day solo endorsement is lapsing or has lapsed.",
    "requirements": "Instructor re-verifies proficiency in required maneuvers and in the specific make/model before re-endorsing — substantively the same check as A.6, but recurring.",
    "validity": {
      "type": "days",
      "value": 90,
      "display": "90 days",
      "trackable": true
    },
    "notes": "The most frequently signed student endorsement after initial solo.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training to qualify for solo flying. I have determined that [he or she] meets the applicable requirements of § 61.87(p) and is proficient to make solo flights in [make and model].",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.8",
    "title": "Solo To/From Another Airport Within 25 NM",
    "citation": "14 CFR § 61.93(b)(1)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student pilot soloing to a specific airport within 25 NM to practice takeoffs/landings (not a cross-country).",
    "requirements": "Instructor determines the student is proficient to make the flight.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Distance-based (25 NM) — do not confuse with the Class B endorsements (A.12/A.13), which are airspace-class-based.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.93(b)(1). I have determined that [he or she] is proficient to practice solo takeoffs and landings at [airport name]. The takeoffs and landings at [airport name] are subject to the following conditions: [list any applicable conditions or limitations].",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.9",
    "title": "Solo Cross-Country Flight (General Authorization)",
    "citation": "14 CFR § 61.93(c)(1),(2)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student pilot before any solo cross-country flight (generally beyond 25 NM with a landing elsewhere).",
    "requirements": "Ground and flight training on cross-country procedures: chart/navigation use, weather recognition, emergency procedures. Instructor determines the student is prepared for the specific type of solo XC considering aircraft, area, and route.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "The broad \"cleared for solo XC generally\" authorization; typically precedes the per-flight endorsement (A.10).",
    "templateText": "I certify that [First name, MI, Last name] has received the required solo cross-country training. I find [he or she] has met the applicable requirements of § 61.93, and is proficient to make solo cross-country flights in a [make and model] aircraft, [aircraft category].",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.10",
    "title": "Solo Cross-Country Flight, Specific Flight",
    "citation": "14 CFR § 61.93(c)(3)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Before each specific solo cross-country flight not previously reviewed by the instructor.",
    "requirements": "Instructor reviews the planned route, weather, and NOTAMs and endorses the logbook for that flight (or a defined series of flights within specified time limits).",
    "validity": {
      "type": "perFlight",
      "value": null,
      "display": "Limited to the specific flight/route endorsed",
      "trackable": false
    },
    "notes": "The \"day-of\" sign-off before a specific student XC launch.",
    "templateText": "I have reviewed the cross-country planning of [First name, MI, Last name]. I find the planning and preparation to be correct to make the solo flight from [departure airport] to [destination airport] via [route of flight] with landings at [names of the airports] in a [make and model] aircraft on [date]. [List any applicable conditions or limitations.]",
    "templateSource": "Verbatim, AC 61-65H, Appendix A (read directly from the FAA's PDF at faa.gov, revision dated 8/27/18).",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.11",
    "title": "Repeated Solo Cross-Country Flights ≤ 50 NM",
    "citation": "14 CFR § 61.93(b)(2)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student flying the same specific route(s) repeatedly to an airport within 50 NM.",
    "requirements": "Instructor has trained the student in both directions over the route, including pattern entry/exit, takeoffs, and landings at the airports used, then endorses for the specific repeated route(s).",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Saves re-endorsing before every repeat flight over the same route.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training in both directions between and at both [airport names]. I have determined that [he or she] is proficient of § 61.93(b)(2) to conduct repeated solo cross-country flights over that route, subject to the following conditions: [list any applicable conditions or limitations].",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.12",
    "title": "Solo Flight in Class B Airspace",
    "citation": "14 CFR § 61.95(a)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student pilot operating solo within Class B airspace generally.",
    "requirements": "Specific ground and flight training in that Class B airspace, then endorsement.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Layered on top of the underlying 90-day solo endorsement currency.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.95(a). I have determined [he or she] is proficient to conduct solo flights in [name of Class B] airspace. [List any applicable conditions or limitations.]",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.13",
    "title": "Solo To/From/At a Specific Class B Airport",
    "citation": "14 CFR § 61.95(b); 14 CFR § 91.131(b)(1)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student pilot operating solo to, from, or at a specific Class B airport.",
    "requirements": "Instructor training and endorsement specific to that airport's Class B operations.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Companion to A.12 — A.12 is the general Class B clearance, A.13 is airport-specific.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.95(b)(1). I have determined that [he or she] is proficient to conduct solo flight operations at [name of airport]. [List any applicable conditions or limitations.]",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.14",
    "title": "TSA Citizenship/Status Verification",
    "citation": "49 CFR § 1552.3(h)",
    "categoryKey": "studentSolo",
    "category": "Student Solo",
    "categorySymbol": "🧑‍✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Non-U.S.-citizen student enrolling in flight training (TSA Alien Flight Student Program).",
    "requirements": "Verification of citizenship/immigration status per TSA rules before flight training begins.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Not a Part 61 airman endorsement — a TSA security requirement CFIs administer. AC 61-65H cites 49 CFR § 1552.3(h); TSA's own Part 1552 paragraph numbering has shifted across rule revisions, so cross-check the current citation directly against 49 CFR Part 1552 before relying on it.",
    "templateText": "I certify that [First name, MI, Last name] has presented me a [type of document presented, such as U.S. birth certificate or U.S. passport, and relevant control or sequential number on the document, if any] establishing that [he or she] is a U.S. citizen or national in accordance with 49 CFR § 1552.3(h).",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.32",
    "title": "Private Pilot Aeronautical Knowledge Test",
    "citation": "14 CFR §§ 61.35(a)(1), 61.103(d), 61.105",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Private pilot certificate applicant, before the knowledge test.",
    "requirements": "Certifies ground training/home study completed on the required aeronautical knowledge areas and readiness for the knowledge test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.105. I have determined that [he or she] is prepared for the [name of] knowledge test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.33",
    "title": "Private Pilot Flight Proficiency/Practical Test",
    "citation": "14 CFR §§ 61.103(f), 61.107(b), 61.109",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Private pilot certificate applicant, before the practical test.",
    "requirements": "Certifies flight proficiency and readiness across the applicable Areas of Operation. Required in addition to the § 61.39 prerequisites endorsements (A.1/A.2).",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required training in accordance with §§ 61.107 and 61.109. I have determined [he or she] is prepared for the [name of] practical test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.34",
    "title": "Commercial Pilot Aeronautical Knowledge Test",
    "citation": "14 CFR §§ 61.35(a)(1), 61.123(c), 61.125",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Commercial pilot certificate applicant, before the knowledge test.",
    "requirements": "Certifies ground training completed on the required commercial-level aeronautical knowledge areas and readiness for the knowledge test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.125. I have determined that [he or she] is prepared for the Commercial Pilot knowledge test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.35",
    "title": "Commercial Pilot Flight Proficiency/Practical Test",
    "citation": "14 CFR §§ 61.123(e), 61.127, 61.129",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Commercial pilot certificate applicant, before the practical test.",
    "requirements": "Certifies flight proficiency and readiness across the commercial-level Areas of Operation. Required in addition to the § 61.39 prerequisites endorsements (A.1/A.2).",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required training of §§ 61.127 and 61.129. I have determined that [he or she] is prepared for the Commercial Pilot practical test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.38",
    "title": "Instrument Rating Aeronautical Knowledge Test",
    "citation": "14 CFR §§ 61.35(a)(1), 61.65(a),(b)",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Instrument rating applicant, before the knowledge test.",
    "requirements": "Certifies ground training completed and readiness for the instrument knowledge test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "AC 61-65H's template is written for airplane; swap in \"Helicopter\" or \"Powered-Lift\" as appropriate to the rating sought.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.65(b). I have determined that [he or she] is prepared for the Instrument–[Airplane/Helicopter/Powered-Lift] knowledge test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.39",
    "title": "Instrument Rating Flight Proficiency/Practical Test",
    "citation": "14 CFR § 61.65(a)(6)",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Instrument rating applicant, before the practical test.",
    "requirements": "Certifies flight proficiency/practical test readiness for the instrument rating.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.65(c) and (d). I have determined [he or she] is prepared for the Instrument–[Airplane/Helicopter/Powered-Lift] practical test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.40",
    "title": "Instrument Rating — § 61.39 Practical Test Prerequisites",
    "citation": "14 CFR § 61.39(a)",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Instrument rating applicant, applying the general § 61.39(a) rule to the instrument practical test.",
    "requirements": "Same 2-calendar-month training-window rule as A.1, applied specifically to the instrument rating, plus the knowledge-deficiency review of A.2 folded into one endorsement.",
    "validity": {
      "type": "conditionalWindow",
      "value": null,
      "display": "2 calendar months preceding the month of application.",
      "trackable": true
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received and logged the required flight time/training of § 61.39(a) in preparation for the practical test within 2 calendar-months preceding the date of the test and has satisfactory knowledge of the subject areas in which [he or she] was shown to be deficient by the FAA Airman Knowledge Test Report. I have determined [he or she] is prepared for the Instrument–[Airplane/Helicopter/Powered-Lift] practical test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.41",
    "title": "Fundamentals of Instructing (FOI) Knowledge Test",
    "citation": "14 CFR § 61.183(d) (training at § 61.185(a)(1))",
    "categoryKey": "cfiCert",
    "category": "CFI Certification",
    "categorySymbol": "🎓",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "CFI applicant, before the FOI knowledge test.",
    "requirements": "Certifies the applicant received the required fundamentals-of-instruction training under § 61.185(a)(1) and is prepared for the FOI knowledge test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Has been a hard requirement at PSI testing centers since September 1, 2024 — one of the most-missed endorsements among CFI candidates using outdated study materials.",
    "templateText": "I certify that [First name, MI, Last name] has received the required fundamentals of instruction training of § 61.185(a)(1). I have determined that [he or she] is prepared for the Fundamentals of Instructing knowledge test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.42",
    "title": "Flight Instructor Aeronautical Knowledge Test",
    "citation": "14 CFR § 61.183(f)",
    "categoryKey": "cfiCert",
    "category": "CFI Certification",
    "categorySymbol": "🎓",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "CFI applicant, before the aeronautical knowledge test for the rating sought.",
    "requirements": "Certifies the required training of § 61.185(a)(2) or (3) (as appropriate to the flight instructor rating sought) and readiness for the knowledge test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.185(a)[(2) or (3), as appropriate to the flight instructor rating sought]. I have determined that [he or she] is prepared for the [name of] knowledge test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.43",
    "title": "Flight Instructor Ground and Flight Proficiency/Practical Test",
    "citation": "14 CFR § 61.183(g)",
    "categoryKey": "cfiCert",
    "category": "CFI Certification",
    "categorySymbol": "🎓",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "CFI applicant, before the practical test (\"recommendation for checkride\").",
    "requirements": "Certifies the required training of § 61.187(b) and ground/flight proficiency readiness for the CFI practical test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Commonly confused with the separate § 61.195(h) endorsement, which certifies the *recommending instructor's own* eligibility to recommend a first-time CFI applicant — not the same thing, and both are needed for an initial CFI applicant.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.187(b). I have determined that [he or she] is prepared for the CFI – [aircraft category and class] practical test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.44",
    "title": "Flight Instructor–Instrument (CFII) Practical Test",
    "citation": "14 CFR §§ 61.183(g), 61.187(a),(b)(7)",
    "categoryKey": "cfiCert",
    "category": "CFI Certification",
    "categorySymbol": "🎓",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "CFI applicant adding an instrument-instructor (CFII) rating.",
    "requirements": "Certifies the required CFII-specific training of § 61.187(b)(7) and readiness for the CFII practical test. There is no separate CFII knowledge test under current Part 61 — only ground/flight training and a practical test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required CFII training of § 61.187(b)(7). I have determined [he or she] is prepared for the CFII [airplane, helicopter, or powered-lift] practical test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.45",
    "title": "Spin Training (Airplane/Glider CFI Applicants)",
    "citation": "14 CFR § 61.183(i)(1)",
    "categoryKey": "other",
    "category": "Other",
    "categorySymbol": "📄",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "CFI applicants seeking airplane or glider category ratings only.",
    "requirements": "Training in stall awareness, spin entry, spins, and spin recovery, with the instructor certifying instructional proficiency (not merely personal recovery competence).",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "Does NOT apply to helicopter, gyroplane, powered-lift, weight-shift, or balloon CFI applicants.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.183(i) in [an airplane / a glider]. I have determined that [he or she] is competent and possesses instructional proficiency in stall awareness, spin entry, spins, and spin recovery procedures.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.46",
    "title": "Helicopter Touchdown Autorotation",
    "citation": "FAA-S-8081-7 (Rotorcraft CFI Practical Test Standards)",
    "categoryKey": "other",
    "category": "Other",
    "categorySymbol": "📄",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Helicopter CFI applicants — the helicopter-category analog to airplane/glider spin training (A.45).",
    "requirements": "Training and demonstrated proficiency in straight-in and 180-degree autorotations to the surface, to instructional standard, letting the examiner accept a logbook endorsement in lieu of a live demonstration during the CFI-helicopter practical test.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "Citation is a Practical Test Standards reference rather than a Part 61 paragraph. AC 61-65H's exact template wording for this item could not be independently confirmed — the text below reflects the substance of the requirement in the AC's own established sentence style, not a confirmed quotation.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training in straight-in and 180-degree autorotations to the surface, to instructional proficiency standards, in a [make and model] helicopter. I have determined that [he or she] is competent and possesses instructional proficiency in touchdown autorotation technique.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.56",
    "title": "R-22/R-44 Ground (Awareness) Training",
    "citation": "SFAR 73 § 2(a)(1) or (2)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "ANY person who wants to manipulate the controls of an R-22 or R-44 for the purpose of flight — including already-rated helicopter pilots who meet the PIC experience thresholds.",
    "requirements": "Ground training in five subject areas, delivered by a CFI authorized under SFAR 73 § 2(b)(5)(iv): (1) energy management, (2) mast bumping, (3) low rotor RPM and rotor stall, (4) low-G conditions/effects/recovery, (5) rotor RPM decay. One session covers both R-22 and R-44.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Alternative pathway: a pilot who completed the Robinson factory safety course may instead receive this endorsement from an FAA Aviation Safety Inspector (not a CFI) in lieu of the ground training itself (§ 2(a)(5)). Low-G ground/awareness training remains required even though actual in-flight low-G maneuver practice was removed from the training requirement in 2024 — intentionally inducing low-G is independently prohibited by ADs 95-11-09 / 95-11-10.",
    "templateText": "I certify that [First name, MI, Last name] has received the ground training required by SFAR 73, section 2(a)(3), covering energy management, mast bumping, low rotor RPM and rotor stall, low-G conditions and recovery, and rotor RPM decay, applicable to the Robinson R-22 and R-44 helicopters.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.57",
    "title": "R-22 Solo Endorsement",
    "citation": "SFAR 73 § 2(b)(3)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student pilot (no rotorcraft category/helicopter class rating) who wants to solo an R-22.",
    "requirements": "At least 20 hours of flight training in an R-22 from an authorized CFI, covering autorotation procedures and energy management, autorotations at a safe entry altitude using maximum-glide configuration, engine/rotor RPM control without the governor, and low rotor RPM recognition/recovery.",
    "validity": {
      "type": "days",
      "value": 90,
      "display": "90 days",
      "trackable": true
    },
    "notes": "Layered on top of, not a replacement for, the standard § 61.87 pre-solo endorsements (A.3/A.4) — a student soloing an R-22 needs both sets.",
    "templateText": "I certify that [First name, MI, Last name] has received the training required by SFAR 73, section 2(b)(3), including not less than 20 hours of flight training in a Robinson R-22 helicopter. I have determined that [he or she] is proficient to solo a Robinson R-22 helicopter. This endorsement expires 90 calendar-days from the date of this training.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.58",
    "title": "R-22 PIC Endorsement (10-Hour Training Pathway)",
    "citation": "SFAR 73 § 2(b)(1)(ii)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Rated helicopter pilot who wants to act as PIC of an R-22 but does not meet the 200-hour/50-hour-in-type experience threshold.",
    "requirements": "10 hours of flight training in the R-22 from an authorized CFI, covering the same abnormal/emergency procedures as the solo endorsement, with the instructor certifying PIC proficiency.",
    "validity": {
      "type": "conditionalWindow",
      "value": null,
      "display": "No fixed expiration, but PIC privileges lapse 12 calendar months after this endorsement's date unless a full SFAR flight review is completed in an R-22 by then (§ 2(b)(1)(iii)).",
      "trackable": true
    },
    "notes": "Alternative to the 200-total/50-in-type experience pathway, which requires no endorsement at all. The 12-month provisional window is a critical date to track.",
    "templateText": "I certify that [First name, MI, Last name] has received the training required by SFAR 73, section 2(b)(1)(ii), including not less than 10 hours of flight training in a Robinson R-22 helicopter. I have determined that [he or she] is proficient to act as pilot in command of a Robinson R-22 helicopter.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.59",
    "title": "R-22 Flight Instructor Authorization",
    "citation": "SFAR 73 § 2(b)(5)(iv)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "FAA Aviation Safety Inspector or Designated Examiner",
    "trigger": "Any CFI who wants to provide training or conduct a flight review in an R-22.",
    "requirements": "CFI must: complete the SFAR ground training; log 200 total helicopter hours with 50 in the R-22; complete flight training on the SFAR abnormal/emergency procedures; and receive an endorsement from an FAA Aviation Safety Inspector or authorized Designated Examiner (not a peer CFI) certifying satisfactory ability to teach these areas.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Without this authorization, even a highly experienced helicopter CFI cannot legally sign any other SFAR 73 endorsement for a student.",
    "templateText": "I certify that [First name, MI, Last name], holder of CFI Certificate No. [certificate number], meets the experience requirements and has completed the ground and flight training specified by SFAR 73, section 2(b)(5)(i) through (iii), and has demonstrated the ability to provide instruction on the subject areas of SFAR 73, section 2(a)(3) and the flight training identified in section 2(b)(5)(iii), in a Robinson R-22 helicopter.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.60",
    "title": "R-22 Flight Review",
    "citation": "SFAR 73 § 2(c)(1),(3)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot due for a § 61.56 flight review who wants it to count toward continued R-22 PIC privileges.",
    "requirements": "Must be conducted in an actual R-22, covering the SFAR ground-training subjects plus R-22-specific abnormal/emergency flight procedures.",
    "validity": {
      "type": "calendarMonths",
      "value": 24,
      "display": "24 calendar months",
      "trackable": true
    },
    "notes": "A review completed in an R-44 does NOT satisfy this for R-22 privileges, and vice versa (see A.64) — a pilot flying both models needs separate reviews for each.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has satisfactorily completed the flight review required by § 61.56 and SFAR 73, section 2(c)(1) and (3), in a Robinson R-22 helicopter on [date].",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.61",
    "title": "R-44 Solo Endorsement",
    "citation": "SFAR 73 § 2(b)(4)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Student pilot (no rotorcraft category/helicopter class rating) who wants to solo an R-44.",
    "requirements": "At least 20 hours of flight training in an R-44 from an authorized CFI, covering the same abnormal/emergency procedure areas as the R-22 with R-44-specific autorotation configurations (both minimum-rate-of-descent and maximum-glide).",
    "validity": {
      "type": "days",
      "value": 90,
      "display": "90 days",
      "trackable": true
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the training required by SFAR 73, section 2(b)(4), including not less than 20 hours of flight training in a Robinson R-44 helicopter. I have determined that [he or she] is proficient to solo a Robinson R-44 helicopter. This endorsement expires 90 calendar-days from the date of this training.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.62",
    "title": "R-44 PIC Endorsement (10-Hour Training Pathway)",
    "citation": "SFAR 73 § 2(b)(2)(ii)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Rated helicopter pilot who wants to act as PIC of an R-44 but does not meet the 200-hour/50-hour-in-type experience threshold.",
    "requirements": "10 hours flight training in a Robinson helicopter, at least 5 of which in the R-44, covering the abnormal/emergency procedure list with both autorotation configurations. Up to 25 R-22 hours may credit toward the 50-hour R-44 experience-pathway threshold.",
    "validity": {
      "type": "conditionalWindow",
      "value": null,
      "display": "No fixed expiration, but PIC privileges lapse 12 calendar months after this endorsement's date unless a full SFAR flight review is completed in an R-44 by then (§ 2(b)(2)(iii)).",
      "trackable": true
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the training required by SFAR 73, section 2(b)(2)(ii), including not less than 10 hours of flight training in a Robinson helicopter, at least 5 hours of which were in the R-44. I have determined that [he or she] is proficient to act as pilot in command of a Robinson R-44 helicopter.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.63",
    "title": "R-44 Flight Instructor Authorization",
    "citation": "SFAR 73 § 2(b)(5)(iv)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "FAA Aviation Safety Inspector or Designated Examiner",
    "trigger": "Any CFI who wants to provide training or conduct a flight review in an R-44.",
    "requirements": "Same structure as the R-22 CFI authorization (A.59), applied with R-44-specific hour-credit rules (200 total helicopter hours, 50 in Robinson helicopters, up to 25 of which may be R-22 time).",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "A single authorization, properly scoped, can cover both R-22 and R-44 instruction if the CFI meets both models' requirements.",
    "templateText": "I certify that [First name, MI, Last name], holder of CFI Certificate No. [certificate number], meets the experience requirements and has completed the ground and flight training specified by SFAR 73, section 2(b)(5)(i) through (iii), and has demonstrated the ability to provide instruction on the subject areas of SFAR 73, section 2(a)(3) and the flight training identified in section 2(b)(5)(iii), in a Robinson R-44 helicopter.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.64",
    "title": "R-44 Flight Review",
    "citation": "SFAR 73 § 2(c)(2),(3)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot due for a § 61.56 flight review who wants it to count toward continued R-44 PIC privileges.",
    "requirements": "Must be conducted in an actual R-44, covering the SFAR ground-training subjects plus R-44-specific abnormal/emergency flight procedures.",
    "validity": {
      "type": "calendarMonths",
      "value": 24,
      "display": "24 calendar months",
      "trackable": true
    },
    "notes": "Does not satisfy R-22 privileges — see A.60.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has satisfactorily completed the flight review required by § 61.56 and SFAR 73, section 2(c)(2) and (3), in a Robinson R-44 helicopter on [date].",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "SFAR-2d",
    "title": "R-22/R-44 Passenger-Carrying Currency",
    "citation": "SFAR 73 § 2(d)",
    "categoryKey": "sfar73",
    "category": "SFAR 73 — Robinson R22/R44",
    "categorySymbol": "🚁",
    "issuer": "Self-logged currency (no CFI signature required)",
    "trigger": "Any PIC of an R-22 or R-44 who wants to carry passengers.",
    "requirements": "Standard § 61.57(a) recency (3 takeoffs and landings in the preceding 90 days) must be satisfied specifically in the R-22 or R-44 being flown — not just \"some helicopter.\"",
    "validity": {
      "type": "days",
      "value": 90,
      "display": "90 days",
      "trackable": true
    },
    "notes": "Not a CFI-signed endorsement — a self-verified currency requirement, but essential to track given the type-specific nature of SFAR 73. Not itemized in AC 61-65H Appendix A since it isn't something a CFI signs.",
    "templateText": null,
    "templateSource": null,
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.65",
    "title": "Flight Review Completion",
    "citation": "14 CFR § 61.56(a),(c)",
    "categoryKey": "flightReview",
    "category": "Flight Review & Currency",
    "categorySymbol": "🔄",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Every certificated pilot, every 24 calendar months, unless an exception under § 61.56(d)/(e)/(f) applies.",
    "requirements": "At least 1 hour flight training + 1 hour ground training covering a review of current Part 91 operating/flight rules and maneuvers/procedures the instructor determines necessary to demonstrate safe exercise of pilot privileges.",
    "validity": {
      "type": "calendarMonths",
      "value": 24,
      "display": "24 calendar months",
      "trackable": true
    },
    "notes": "No \"failed\" state exists — if the pilot doesn't pass, the CFI simply does not endorse; no logbook entry reflecting unsatisfactory performance should be made. For Robinson R22/R44 PIC privileges, SFAR 73 requires the review be taken in the specific make (R22 review does not cover R44, and vice versa).",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has satisfactorily completed a flight review of § 61.56(a) on [date].",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.66",
    "title": "WINGS Pilot Proficiency Program Phase",
    "citation": "14 CFR § 61.56(e)",
    "categoryKey": "flightReview",
    "category": "Flight Review & Currency",
    "categorySymbol": "🔄",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Pilot completing a WINGS Pilot Proficiency Program phase as a substitute for a standalone flight review.",
    "requirements": "Completion of a full WINGS phase within the preceding 24 calendar months satisfies the flight review requirement.",
    "validity": {
      "type": "calendarMonths",
      "value": 24,
      "display": "24 calendar months",
      "trackable": true
    },
    "notes": "AC 61-65H's exact template wording for this item could not be independently confirmed; the text below is modeled on the FAASTeam's own WINGS completion language, not a confirmed AC quotation.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has satisfactorily completed Phase [number] of the FAA Safety Team WINGS Pilot Proficiency Program in accordance with § 61.56(e) on [date].",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.67",
    "title": "Instrument Proficiency Check (IPC)",
    "citation": "14 CFR § 61.57(d)",
    "categoryKey": "flightReview",
    "category": "Flight Review & Currency",
    "categorySymbol": "🔄",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Instrument-rated pilot who has lapsed instrument currency beyond the further 6-month self-requalification window under § 61.57(c).",
    "requirements": "IPC covers the applicable Areas of Operation in the Instrument ACS. Currency itself requires 6 approaches, holding, and course intercept/tracking within the preceding 6 calendar months; a further 6-month grace window allows requalification by logging tasks alone; only after that lapses is an IPC mandatory.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "Same \"no unsatisfactory entry\" rule as the flight review. An IPC does not automatically satisfy a flight review, and vice versa, though a single flight can sometimes be structured to cover both.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has satisfactorily completed the instrument proficiency check of § 61.57(d) in a [make and model of aircraft] on [date].",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.68",
    "title": "PIC in Complex Airplane",
    "citation": "14 CFR § 61.31(e)",
    "categoryKey": "aircraft",
    "category": "Additional Aircraft (§ 61.31)",
    "categorySymbol": "✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before acting as PIC of a complex airplane (retractable gear + flaps + controllable-pitch propeller — all three required).",
    "requirements": "Ground and flight training from an authorized instructor certifying proficiency in the operation and systems of a complex airplane.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "Airplane-category only — there is no \"complex helicopter\" endorsement under § 61.31.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the required training of § 61.31(e) in a [make and model of complex airplane]. I have determined that [he or she] is proficient in the operation and systems of a complex airplane.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.69",
    "title": "PIC in High-Performance Airplane",
    "citation": "14 CFR § 61.31(f)",
    "categoryKey": "aircraft",
    "category": "Additional Aircraft (§ 61.31)",
    "categorySymbol": "✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before acting as PIC of an airplane with an engine rated over 200 HP.",
    "requirements": "Ground and flight training certifying proficiency in the operation and systems of a high-performance airplane.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "Independent of the complex endorsement — an aircraft can be high-performance without being complex, or both. Airplane-specific; no FAA-required \"high-performance helicopter\" endorsement exists (any informal insurer/operator practice to the contrary is not a regulatory requirement).",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the required training of § 61.31(f) in a [make and model of high performance airplane]. I have determined that [he or she] is proficient in the operation and systems of a high performance airplane.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.70",
    "title": "PIC in Pressurized (High-Altitude) Aircraft",
    "citation": "14 CFR § 61.31(g)",
    "categoryKey": "aircraft",
    "category": "Additional Aircraft (§ 61.31)",
    "categorySymbol": "✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before acting as PIC of a pressurized aircraft with a service ceiling/max operating altitude above 25,000 ft MSL.",
    "requirements": "Ground training covering physiological aspects (hypoxia, gas expansion, decompression sickness) and physical phenomena of decompression.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "Applies only to pressurized aircraft above the 25,000 ft threshold — does not apply to unpressurized high-altitude operations (a § 91.211 oxygen issue, not an endorsement issue).",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the required training of § 61.31(g) in a [make and model of pressurized aircraft]. I have determined that [he or she] is proficient in the operation and systems of a pressurized aircraft.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.71",
    "title": "PIC in Tailwheel Airplane",
    "citation": "14 CFR § 61.31(i)",
    "categoryKey": "aircraft",
    "category": "Additional Aircraft (§ 61.31)",
    "categorySymbol": "✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before acting as PIC of a tailwheel (conventional-gear) airplane.",
    "requirements": "Flight training in normal/crosswind takeoffs and landings, wheel landings (unless not appropriate to the aircraft), and go-arounds.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "One endorsement covers any tailwheel airplane — no make/model restriction. § 61.31(i)(2) provides a historical logged-time exception; verify current text for that edge case.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the required training of § 61.31(i) in a [make and model of tailwheel airplane]. I have determined that [he or she] is proficient in the operation of a tailwheel airplane.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.72",
    "title": "Solo PIC Without Category/Class Rating (Rated Pilot Adding a Category)",
    "citation": "14 CFR § 61.31(d)(2)",
    "categoryKey": "aircraft",
    "category": "Additional Aircraft (§ 61.31)",
    "categorySymbol": "✈️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "A certificated pilot training toward an additional category/class rating who needs to solo in that new category/class before earning the rating.",
    "requirements": "Instructor endorsement certifying training received and proficiency to solo the specific make/model — parallels a student pre-solo/solo endorsement but applies to already-certificated pilots adding a category or class.",
    "validity": {
      "type": "conditionalWindow",
      "value": null,
      "display": "Exact validity/renewal period not confirmed against current AC text — verify before relying on a hard-coded expiration.",
      "trackable": true
    },
    "notes": "Directly relevant to an airplane-rated pilot adding helicopter category (or vice versa).",
    "templateText": "I certify that [First name, MI, Last name] has received the training as required by § 61.31(d)(2) to serve as a pilot in command in a [specific category and class of aircraft]. I have determined that [he or she] is prepared to solo that [make and model] aircraft. Limitations: [optional].",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.73",
    "title": "Retesting After Knowledge or Practical Test Failure",
    "citation": "14 CFR § 61.49",
    "categoryKey": "knowledge",
    "category": "Knowledge & Practical Test",
    "categorySymbol": "📋",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any applicant who failed a knowledge or practical test and needs additional training before retesting.",
    "requirements": "Certifies additional training was given in each area of deficiency and the applicant is now prepared for the retest.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the additional [flight and/or ground, as appropriate] training as required by § 61.49. I have determined that [he or she] is prepared for the [name of] knowledge/practical test.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.74",
    "title": "Additional Aircraft Category or Class Rating (Non-ATP)",
    "citation": "14 CFR § 61.63(b) or (c)",
    "categoryKey": "catClassType",
    "category": "Category / Class / Type",
    "categorySymbol": "📚",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Certificated pilot adding a new category (e.g., airplane pilot adding helicopter) or class rating, below ATP level.",
    "requirements": "Instructor recommendation after required training/experience for the certificate level held; applicant must pass the practical test for the new category/class.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "The relevant endorsement for cross-category transitions such as a fixed-wing CFI's student adding helicopter, or vice versa. Some knowledge-test waiver conditions may apply under § 61.63 — verify paragraph-by-paragraph if auto-determining knowledge-test necessity. AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.63(b) [or (c)]. I have determined that [he or she] is prepared for the practical test for the [category and class] rating.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.75",
    "title": "Type Rating Only (Already Holds Category/Class, Non-ATP)",
    "citation": "14 CFR § 61.63(d)(2)",
    "categoryKey": "catClassType",
    "category": "Category / Class / Type",
    "categorySymbol": "📚",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Pilot who already holds the appropriate category/class and is adding only a type rating.",
    "requirements": "Required training/logbook or training-record endorsements; pass the applicable practical test.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": null,
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.63(d)(2) for an addition of a [name of] type rating.",
    "templateSource": "Reproduced from AC 61-65H, Appendix A, via secondary sources that quote the AC directly; citation and item number confirmed against the AC's own table of contents, but not independently re-verified character-for-character against the FAA PDF.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.76",
    "title": "Type Rating Concurrent With Category/Class (Non-ATP)",
    "citation": "14 CFR § 61.63(d)(2)",
    "categoryKey": "catClassType",
    "category": "Category / Class / Type",
    "categorySymbol": "📚",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Pilot adding a type rating at the same time as the underlying category/class rating.",
    "requirements": "Same underlying structure as A.75, combined with the category/class addition requirements.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name] has received the required training of § 61.63(d)(2) for the addition of the [category and class] rating and [name of] type rating concurrently. I have determined that [he or she] is prepared for the practical test.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "61.195h",
    "title": "Recommending Instructor's Eligibility (First-Time CFI Applicant)",
    "citation": "14 CFR § 61.195(h)(2),(3)",
    "categoryKey": "cfiCert",
    "category": "CFI Certification",
    "categorySymbol": "🎓",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "The flight instructor recommending someone for their FIRST flight instructor certificate (not additional ratings on an existing CFI certificate).",
    "requirements": "The recommending instructor must meet one of three pathways: (1) held a CFI certificate ≥24 calendar months AND given ≥200 hours of flight training as a CFI (80 hours for gliders); (2) trained and endorsed ≥5 practical-test applicants in the preceding 24 calendar months with ≥80% passing on the first attempt; or (3) graduated from an FAA-approved Part 141/142 flight-instructor enhanced-qualification program.",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "AC 61-65H discusses this § 61.195(h) requirement in its body text (the flight-instructor-qualifications discussion) but does not include it as a numbered Appendix A sample endorsement. It is legally required and is one of the most-missed items causing initial CFI applicants to be turned away at the start of the oral. Distinct from A.43, which certifies the applicant's own readiness rather than the recommending instructor's eligibility.",
    "templateText": "I certify that I am qualified to recommend a first-time flight instructor applicant in accordance with 14 CFR § 61.195(h). [Optionally cite the specific pathway, e.g., § 61.195(h)(2)(i).]",
    "templateSource": "Not a numbered sample endorsement in AC 61-65H Appendix A. AC 61-65H discusses the underlying requirement in its body text, but provides no official template -- the wording here is a practitioner convention, not FAA template text.",
    "trackKey": "general",
    "track": "General (Any Category)"
  },
  {
    "id": "A.86",
    "title": "NVG Ground Training",
    "citation": "14 CFR § 61.31(k)(1)",
    "categoryKey": "nvg",
    "category": "Night Vision Goggles (§ 61.31(k))",
    "categorySymbol": "🌙",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before acting as PIC of an aircraft using night vision goggles (NVGs).",
    "requirements": "Ground training in NVG operating principles, limitations, techniques, and the physiology of night vision, per § 61.31(k)(1)(i) through (v).",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "Predominantly a helicopter discipline (EMS, law enforcement, utility work) though § 61.31(k) is written for \"aircraft\" generically, not helicopter-specific. AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the ground training required by § 61.31(k)(1) in the use of night vision goggles.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.87",
    "title": "NVG Flight Training / Proficiency",
    "citation": "14 CFR § 61.31(k)(2)",
    "categoryKey": "nvg",
    "category": "Night Vision Goggles (§ 61.31(k))",
    "categorySymbol": "🌙",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before acting as PIC of an aircraft using NVGs, after completing the ground training (A.86).",
    "requirements": "Flight training in NVG proficiency tasks (preflight, normal/abnormal/emergency NVG procedures, unaided-to-aided transitions, etc.) in the specific make and model, with the instructor certifying proficiency.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the flight training required by § 61.31(k)(2) in a [make and model] aircraft. I have determined that [he or she] is proficient in the use of night vision goggles for night flight operations.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.88",
    "title": "Endorsement to Provide NVG Training",
    "citation": "14 CFR § 61.195(k)(7)",
    "categoryKey": "nvg",
    "category": "Night Vision Goggles (§ 61.31(k))",
    "categorySymbol": "🌙",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any CFI who wants to provide NVG ground or flight training to other pilots.",
    "requirements": "The instructor must themselves meet the NVG training/experience requirements before being authorized to teach NVG operations to others.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], meets the requirements of § 61.195(k)(7) and is qualified to provide training in the use of night vision goggles.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "heli",
    "track": "Helicopter"
  },
  {
    "id": "A.89",
    "title": "EFVS Ground Training",
    "citation": "14 CFR § 61.66(a)",
    "categoryKey": "efvs",
    "category": "Enhanced Flight Vision System (§ 61.66)",
    "categorySymbol": "👁️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before using an enhanced flight vision system (EFVS) to conduct approach operations below DA/DH or MDA.",
    "requirements": "Ground training on EFVS operating principles, limitations, and the specific system installed in the aircraft to be flown.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "Predominantly a turbine/jet fixed-wing discipline (used to descend below DA/DH or MDA using EFVS in lieu of natural vision) though § 61.66 is written for \"aircraft\" generically. AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the ground training required by § 61.66(a) in the use of an enhanced flight vision system.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.90",
    "title": "EFVS Flight Training",
    "citation": "14 CFR § 61.66(b)",
    "categoryKey": "efvs",
    "category": "Enhanced Flight Vision System (§ 61.66)",
    "categorySymbol": "👁️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot before using EFVS to conduct approach operations below DA/DH or MDA, after completing ground training (A.89).",
    "requirements": "Flight training in the specific make and model equipped with the EFVS, with the instructor certifying proficiency in its use to descend below DA/DH or MDA using enhanced flight visibility.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the flight training required by § 61.66(b) in a [make and model] aircraft equipped with an enhanced flight vision system. I have determined that [he or she] is proficient in the use of that system to operate below the DA/DH or MDA using enhanced flight visibility.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.91",
    "title": "EFVS Ground and Flight Training, Combined",
    "citation": "14 CFR § 61.66(a),(b)",
    "categoryKey": "efvs",
    "category": "Enhanced Flight Vision System (§ 61.66)",
    "categorySymbol": "👁️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot completing EFVS ground and flight training in a single combined course of instruction.",
    "requirements": "Same substance as A.89/A.90, delivered and endorsed together rather than as two separate endorsements.",
    "validity": {
      "type": "oneTime",
      "value": null,
      "display": "One-time — no expiration once issued",
      "trackable": false
    },
    "notes": "AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the ground and flight training required by § 61.66(a) and (b) in a [make and model] aircraft equipped with an enhanced flight vision system. I have determined that [he or she] is proficient in its use.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  },
  {
    "id": "A.92",
    "title": "EFVS Supplementary/Recurrent Training",
    "citation": "14 CFR § 61.66(c)",
    "categoryKey": "efvs",
    "category": "Enhanced Flight Vision System (§ 61.66)",
    "categorySymbol": "👁️",
    "issuer": "Certificated Flight Instructor (CFI)",
    "trigger": "Any pilot due for recurrent EFVS training under § 61.66(c).",
    "requirements": "Supplementary ground and/or flight training to maintain EFVS proficiency on the recurrent schedule required by § 61.66(c).",
    "validity": {
      "type": "notStated",
      "value": null,
      "display": "No expiration stated in the regulation",
      "trackable": false
    },
    "notes": "AC 61-65H's exact template wording for this item could not be independently confirmed; verify before use.",
    "templateText": "I certify that [First name, MI, Last name], [grade of pilot certificate], [certificate number], has received the supplementary training required by § 61.66(c) in the use of an enhanced flight vision system in a [make and model] aircraft.",
    "templateSource": "Suggested wording only. This app's research could not independently confirm AC 61-65H's exact phrasing for this item. Verify against your own current copy of the AC before signing an actual endorsement.",
    "trackKey": "fixed",
    "track": "Fixed Wing"
  }
];

var CATEGORY_ORDER = ["studentSolo", "knowledge", "flightReview", "aircraft", "catClassType", "sfar73", "nvg", "efvs", "cfiCert", "other"];
var CATEGORY_DISPLAY = {"studentSolo": "Student Solo", "knowledge": "Knowledge & Practical Test", "flightReview": "Flight Review & Currency", "aircraft": "Additional Aircraft (§ 61.31)", "catClassType": "Category / Class / Type", "sfar73": "SFAR 73 — Robinson R22/R44", "nvg": "Night Vision Goggles (§ 61.31(k))", "efvs": "Enhanced Flight Vision System (§ 61.66)", "cfiCert": "CFI Certification", "other": "Other"};
var TRACK_DISPLAY = {"heli": "Helicopter", "fixed": "Fixed Wing", "general": "General (Any Category)"};
